    - name: Deploy to VPS via SSH
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
        APP_DIR: ${{ secrets.APP_DIR }}
      run: |
        echo "$EC2_KEY" > private_key.pem
        chmod 600 private_key.pem

        if ! ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"; then
          echo "Failed to establish SSH connection"
          exit 1
        fi

        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd ~/application || {
            echo "Directory ~/application not found. Exiting.";
            exit 1;
          }

          git pull origin main

          ./mvnw clean package

          cp target/*.jar ~/application/church-financial.jar

          sudo systemctl daemon-reload
          sudo systemctl restart church-financial 

          echo "Deployment completed and service restarted!"
        EOF

