name: Deploy application
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Create .env file
      run: |
        echo "APPLICATION_NAME=${{ secrets.APPLICATION_NAME }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

    - name: Build the application
      run: |
        ./mvnw clean package -DskipTests

    - name: Unit tests
      run: |
        ./mvnw test

    - name: Deploy to VPS via SSH
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
        APP_DIR: ${{ secrets.APP_DIR }}
      run: |
        echo "$EC2_KEY" > private_key.pem
        chmod 600 private_key.pem

        if ! ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'SSH connection successful'"; then
          echo "Failed to establish SSH connection"
          exit 1
        fi

        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd ~/application || {
            echo "Directory ~/application not found. Exiting.";
            exit 1;
          }

          echo "Pulling latest code..."
          git pull origin main
          
          echo "Building new JAR..."
          ./mvnw clean package -DskipTests
          
          echo "stoping the application"
          sudo systemctl stop church-financial

          echo "removing the old jar file"
          rm -rf /root/application/church-financial.jar

          echo "Updating deployed jar..."
          cp target/*.jar /root/application/church-financial.jar
          
          echo "Restarting service..."
          systemctl daemon-reload
          systemctl start church-financial
          
          echo "Deployment successful!"
        EOF
